highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
#port: 3000
safe: true

# Prod
#url: http://dotps1.github.io/PSGist
# Dev
url: http://localhost:4000
baseurl: ""
title: PSGist
author: Thomas Malkewitz
description: PowerShell Module that interfaces with GitHub Gists.
#disqus: username
#google_analytics: