#http://www.appveyor.com/docs/appveyor-yml
version: 1.4.1.1
os: WMF 5
skip_commits:
  message: /updated readme.*/
install:
  - ps: Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Confirm:$false -Force -ErrorAction Stop
  - ps: Install-Module -Name Pester -Confirm:$false -Force -ErrorAction SilentlyContinue
  - ps: Install-Module -Name PSScriptAnalyzer -Confirm:$false -Force -ErrorAction SilentlyContinue
build: off
test_script:
  - ps: . .\Tests\_appveyor.pester.ps1