# http://www.appveyor.com/docs/appveyor-yml

version: 2.5.{build}
os: WMF 5
skip_commits:
  message: /updated readme.*/
install:
  - ps: Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Confirm:$false -Force -ErrorAction Stop
  - ps: Install-Module -Name Pester -Confirm:$false -Force -ErrorAction SilentlyContinue
  - ps: Install-Module -Name PSScriptAnalyzer -Confirm:$false -Force -ErrorAction SilentlyContinue
build: off
test_script:
  - ps: . .\Invoke-AppveyorBuild.ps1
environment:
  powershell_gallery_api_token:
    secure: feZG1n6/I0hDzxw9VWtlUph94caZUYw3denU0TLudvgWX9cG/jkjDLOT8ixd02P4
notifications:
  - provider: Slack
    incoming_webhook:
      secure: AbntoBWt4UaZffU0mBhQjuXCQAIegqF1NtTVdnFyinHHS23C+b/r4/lWGDzneboipU5R9/6ti/x1p1ceodafH5iv+il9EyS87/M8TaE3hf8=
  